# -*- coding: utf-8 -*-
"""Project_Data_Pull.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0dE0VgUVZ064iZMy9zairTIaREq41Z0
"""

#pip install hra-api-client #uncomment pip to install api from humanatlas website from bruce
import json

!cat /usr/local/lib/python3.10/dist-packages/hra_api_client/api_client.py

import requests
base_url = 'https://apps.humanatlas.io/api/v1'

response = requests.get(f'{base_url}/biomarker-tree-model')
biomarker_terms = response.json()

with open('biomarker_terms.json', 'w') as f:
    json.dump(biomarker_terms, f, indent=4)

print("Biomarker Terms Data Saved!")

biomarker_terms